const scenarios = {
  ops: {label:'OPERATIONS',title:'Convert expert handoffs into reusable standard work.',narrative:'Use structured context and human review to turn recurring operating knowledge into a dependable first draft, checklist, and escalation path.',ai:'Draft, structure, compare',authority:'Process owner approves',governance:'Approved sources; no confidential leakage',measure:'Cycle time, completeness, reuse',motion:'Demo → practice → office hours',verdict:'Standardize',heroVerdict:'Ready to standardize',heroScenario:'Operations knowledge handoff',colors:['#7a62ff','#46a4ff','#22dfca']},
  talent: {label:'TALENT OPERATIONS',title:'Turn role context into a consistent candidate assessment workflow.',narrative:'Help recruiting teams move from generic prompting to structured role context, evidence-based comparison, human judgment, and traceable decisions.',ai:'Synthesize, compare, prepare',authority:'Recruiter and hiring manager decide',governance:'No sensitive inference; evidence remains attributable',measure:'Intake speed, consistency, rework',motion:'Role clinic → template → calibration',verdict:'Pilot with controls',heroVerdict:'Pilot with controls',heroScenario:'Role-context assessment workflow',colors:['#6276ff','#52b2ff','#36ded4']},
  delivery: {label:'SALES & DELIVERY',title:'Convert discovery into an actionable client-work brief.',narrative:'Use ChatGPT to organize notes, surface open assumptions, draft a structured response, and preserve explicit human ownership of commitments.',ai:'Organize, challenge, draft',authority:'Account and delivery owners commit',governance:'Client data and claims remain bounded',measure:'Handoff speed, clarity, revision load',motion:'Live demo → paired use → review',verdict:'Scale after proof',heroVerdict:'Scale after proof',heroScenario:'Discovery-to-delivery brief',colors:['#3a94ff','#51d2dc','#43e0b2']},
  support: {label:'SUPPORT',title:'Turn recurring issues into earlier, clearer response guidance.',narrative:'Synthesize approved knowledge, identify missing context, draft a response path, and escalate when confidence or consequence requires human judgment.',ai:'Retrieve, summarize, route',authority:'Support owner resolves or escalates',governance:'Approved knowledge; no unsupported diagnosis',measure:'Response time, recurrence, resolution quality',motion:'Case replay → coaching → adoption',verdict:'Standardize selectively',heroVerdict:'Standardize selectively',heroScenario:'Recurring-issue response guidance',colors:['#966bff','#57a5ff','#34d8c6']}
};
const fieldIds={label:'scenarioLabel',title:'scenarioTitle',narrative:'scenarioNarrative',ai:'aiRole',authority:'authority',governance:'governance',measure:'measure',motion:'motion',verdict:'verdict'};
const prefersReducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const mobileRendererQuery=window.matchMedia('(max-width: 980px), (pointer: coarse) and (max-width: 1100px)');
const stage=document.getElementById('transformer');
const canvas=document.getElementById('capabilityField');
const announcement=document.getElementById('scenarioAnnouncement');
let visual=null;let selectedScenario='ops';let animationToken=0;
function hexToRgb(hex){const n=Number.parseInt(hex.slice(1),16);return[(n>>16)/255,((n>>8)&255)/255,(n&255)/255]}
function perspective(out,fovy,aspect,near,far){const f=1/Math.tan(fovy/2);out.fill(0);out[0]=f/aspect;out[5]=f;out[10]=(far+near)/(near-far);out[11]=-1;out[14]=2*far*near/(near-far);return out}
function lookAt(out,eye,center,up){let zx=eye[0]-center[0],zy=eye[1]-center[1],zz=eye[2]-center[2];let len=Math.hypot(zx,zy,zz)||1;zx/=len;zy/=len;zz/=len;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx;len=Math.hypot(xx,xy,xz)||1;xx/=len;xy/=len;xz/=len;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;out[0]=xx;out[1]=yx;out[2]=zx;out[3]=0;out[4]=xy;out[5]=yy;out[6]=zy;out[7]=0;out[8]=xz;out[9]=yz;out[10]=zz;out[11]=0;out[12]=-(xx*eye[0]+xy*eye[1]+xz*eye[2]);out[13]=-(yx*eye[0]+yy*eye[1]+yz*eye[2]);out[14]=-(zx*eye[0]+zy*eye[1]+zz*eye[2]);out[15]=1;return out}
function createProgram(gl,vs,fs){const compile=(type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(shader)||'Shader compilation failed');return shader};const program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vs));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program)||'Program linking failed');return program}
function seeded(i){const x=Math.sin(i*12.9898)*43758.5453;return x-Math.floor(x)}
