class CapabilityFunnel{
  constructor(targetCanvas){this.canvas=targetCanvas;this.gl=targetCanvas.getContext('webgl2',{alpha:false,antialias:true,powerPreference:'high-performance',premultipliedAlpha:true});if(!this.gl)throw new Error('WebGL2 unavailable');this.progress=1;this.startTime=0;this.duration=4200;this.raf=0;this.palette=scenarios.ops.colors.map(hexToRgb);this.projection=new Float32Array(16);this.view=new Float32Array(16);lookAt(this.view,[0,.45,7.1],[0,.05,0],[0,1,0]);this.init();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(targetCanvas.parentElement)}
  init(){const gl=this.gl;
    this.surfaceProgram=createProgram(gl,`#version 300 es
      precision highp float;layout(location=0)in vec4 aData;uniform mat4 uProjection,uView;uniform float uProgress,uTime;uniform vec3 uA,uC;out vec3 vColor;out float vAlpha;out float vEdge;
      void main(){float theta=aData.x;float v=aData.y;float r=.38+2.20*pow(v,.72);r+=.12*sin(v*3.14159)*sin(theta*2.0+v*5.5+uTime*.22);float twist=(1.0-v)*1.18+.14*sin(v*3.14159);float a=theta+twist;float x=r*cos(a)+.26*sin(v*3.14159*1.15);float z=r*.58*sin(a);float y=mix(-1.46,1.30,v);float settle=smoothstep(.0,.72,uProgress);x*=mix(.91,1.0,settle);z*=mix(.82,1.0,settle);vec4 vp=uView*vec4(x,y,z,1.0);gl_Position=uProjection*vp;float side=cos(a)*.5+.5;vColor=mix(uA,uC,side);vAlpha=(.11+.15*(1.0-v))*(.58+.42*settle);vEdge=aData.z;}`,
      `#version 300 es
      precision highp float;in vec3 vColor;in float vAlpha;in float vEdge;out vec4 outColor;void main(){float glow=.72+.28*vEdge;outColor=vec4(vColor*(1.18+glow*.28),vAlpha*glow);}`);
    this.lineProgram=createProgram(gl,`#version 300 es
      precision highp float;layout(location=0)in vec4 aData;uniform mat4 uProjection,uView;uniform float uProgress,uTime;uniform vec3 uA,uC;out vec3 vColor;out float vAlpha;
      void main(){float theta=aData.x;float v=aData.y;float r=.38+2.20*pow(v,.72);r+=.12*sin(v*3.14159)*sin(theta*2.0+v*5.5+uTime*.22);float twist=(1.0-v)*1.18+.14*sin(v*3.14159);float a=theta+twist;float x=r*cos(a)+.26*sin(v*3.14159*1.15);float z=r*.58*sin(a);float y=mix(-1.46,1.30,v);vec4 vp=uView*vec4(x,y,z,1.0);gl_Position=uProjection*vp;float side=cos(a)*.5+.5;vColor=mix(uA,uC,side);float rim=step(.965,v)*.56+(1.0-step(.075,v))*.38;vAlpha=.18+.34*aData.z+rim;}`,
      `#version 300 es
      precision highp float;in vec3 vColor;in float vAlpha;out vec4 outColor;void main(){outColor=vec4(vColor*1.6,vAlpha);}`);
    this.particleProgram=createProgram(gl,`#version 300 es
      precision highp float;layout(location=0)in vec4 aData;uniform mat4 uProjection,uView;uniform float uProgress,uTime;uniform vec3 uA,uB,uC;out vec3 vColor;out float vAlpha;
      float ease(float x){return x*x*(3.0-2.0*x);}float hash(float n){return fract(sin(n)*43758.5453123);}void main(){float seed=aData.x;float lane=aData.y;float travel=ease(clamp((uProgress-seed*.22)/.78,0.0,1.0));float settle=smoothstep(.84,1.0,uProgress);float p=mix(travel,seed,settle);vec3 pos;float c;
      if(p<.27){float q=p/.27;pos=vec3(mix(-4.9,-2.45,q),mix(lane*.82,.92+lane*.22,q)+sin(seed*90.0+uTime*1.2)*.08,mix((hash(seed*43.0)-.5)*1.32,0.0,q));c=q*.14;}
      else if(p<.80){float q=(p-.27)/.53;float v=1.0-q*.94;float theta=3.14159+lane*.18+(seed-.5)*.44+q*7.8;float r=.38+2.20*pow(v,.72);r+=.12*sin(v*3.14159)*sin(theta*2.0+v*5.5);float twist=(1.0-v)*1.18+.14*sin(v*3.14159);float a=theta+twist;pos=vec3(r*cos(a)+.26*sin(v*3.14159*1.15),mix(1.30,-1.32,q),r*.58*sin(a));c=.14+q*.68;}
      else{float q=(p-.80)/.20;pos=vec3(mix(.22,3.25+seed*1.55,q),mix(-1.32,lane*.62,q)+sin((q+seed)*18.0)*.032,mix(0.0,(hash(seed*121.0)-.5)*.12,q));c=.82+q*.18;}
      vec4 vp=uView*vec4(pos,1.0);gl_Position=uProjection*vp;gl_PointSize=aData.w*(5.4/max(1.0,-vp.z));vec3 sourceColor=mix(uA,uB,lane*.5+.5);vColor=mix(sourceColor,uC,c);vAlpha=(.34+.58*hash(seed*211.0))*smoothstep(0.0,.06,travel);}`,
      `#version 300 es
      precision highp float;in vec3 vColor;in float vAlpha;out vec4 outColor;void main(){vec2 uv=gl_PointCoord-.5;float d=length(uv);if(d>.5)discard;float g=pow(smoothstep(.5,0.0,d),2.0);outColor=vec4(vColor*(1.2+g*.78),vAlpha*g);}`);
    this.buildGeometry();gl.enable(gl.BLEND);gl.enable(gl.DEPTH_TEST);this.resize()}
  buildGeometry(){const gl=this.gl,rings=42,segments=110,vertices=[],indices=[],lines=[];for(let j=0;j<=rings;j++){const v=j/rings;for(let i=0;i<=segments;i++){const theta=i/segments*Math.PI*2;vertices.push(theta,v,(i%9===0||j%6===0)?1:0,0)}}for(let j=0;j<rings;j++){for(let i=0;i<segments;i++){const a=j*(segments+1)+i,b=a+1,c=(j+1)*(segments+1)+i,d=c+1;indices.push(a,c,b,b,c,d)}}this.surfaceBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.surfaceBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);this.indexBuffer=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.indexBuffer);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint32Array(indices),gl.STATIC_DRAW);this.indexCount=indices.length;for(let j=0;j<=rings;j+=4){const v=j/rings;for(let i=0;i<segments;i++)lines.push(i/segments*Math.PI*2,v,1,0,(i+1)/segments*Math.PI*2,v,1,0)}for(let i=0;i<segments;i+=8){const theta=i/segments*Math.PI*2;for(let j=0;j<rings;j++)lines.push(theta,j/rings,1,0,theta,(j+1)/rings,1,0)}this.lineBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.lineBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(lines),gl.STATIC_DRAW);this.lineCount=lines.length/4;const count=2900,data=new Float32Array(count*4);for(let i=0;i<count;i++){const lane=(i%3)-1,seed=(i+seeded(i)*.8)/count;data.set([seed,lane,seeded(i+17),6+seeded(i+31)*11],i*4)}this.particleBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.particleBuffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);this.particleCount=count}
  setPalette(colors){this.palette=colors.map(hexToRgb)}
  resize(){const rect=this.canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,1.75),width=Math.max(1,Math.round(rect.width*dpr)),height=Math.max(1,Math.round(rect.height*dpr));if(this.canvas.width!==width||this.canvas.height!==height){this.canvas.width=width;this.canvas.height=height;this.gl.viewport(0,0,width,height);perspective(this.projection,Math.PI/4.2,width/height,.1,40)}this.render(performance.now())}
  replay(){cancelAnimationFrame(this.raf);stage.classList.remove('settled');this.startTime=performance.now();this.progress=prefersReducedMotion.matches?1:0;if(prefersReducedMotion.matches){this.render(this.startTime+this.duration);stage.classList.add('settled');return}this.loop(this.startTime)}
  loop=(now)=>{const t=Math.min(1,(now-this.startTime)/this.duration);this.progress=1-Math.pow(1-t,3);this.render(now);if(t<1)this.raf=requestAnimationFrame(this.loop);else stage.classList.add('settled')}
  render(now){const gl=this.gl,time=now*.001;gl.clearColor(.008,.024,.055,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(this.surfaceProgram);this.setCommon(this.surfaceProgram,time);gl.bindBuffer(gl.ARRAY_BUFFER,this.surfaceBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,16,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.indexBuffer);gl.drawElements(gl.TRIANGLES,this.indexCount,gl.UNSIGNED_INT,0);gl.depthMask(false);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.useProgram(this.lineProgram);this.setCommon(this.lineProgram,time);gl.bindBuffer(gl.ARRAY_BUFFER,this.lineBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,16,0);gl.drawArrays(gl.LINES,0,this.lineCount);gl.useProgram(this.particleProgram);gl.uniformMatrix4fv(gl.getUniformLocation(this.particleProgram,'uProjection'),false,this.projection);gl.uniformMatrix4fv(gl.getUniformLocation(this.particleProgram,'uView'),false,this.view);gl.uniform1f(gl.getUniformLocation(this.particleProgram,'uProgress'),this.progress);gl.uniform1f(gl.getUniformLocation(this.particleProgram,'uTime'),time);gl.uniform3fv(gl.getUniformLocation(this.particleProgram,'uA'),this.palette[0]);gl.uniform3fv(gl.getUniformLocation(this.particleProgram,'uB'),this.palette[1]);gl.uniform3fv(gl.getUniformLocation(this.particleProgram,'uC'),this.palette[2]);gl.bindBuffer(gl.ARRAY_BUFFER,this.particleBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,16,0);gl.drawArrays(gl.POINTS,0,this.particleCount)}
  setCommon(program,time){const gl=this.gl;gl.uniformMatrix4fv(gl.getUniformLocation(program,'uProjection'),false,this.projection);gl.uniformMatrix4fv(gl.getUniformLocation(program,'uView'),false,this.view);gl.uniform1f(gl.getUniformLocation(program,'uProgress'),this.progress);gl.uniform1f(gl.getUniformLocation(program,'uTime'),time);gl.uniform3fv(gl.getUniformLocation(program,'uA'),this.palette[0]);gl.uniform3fv(gl.getUniformLocation(program,'uC'),this.palette[2])}
}
