const scenarios={
  ops:{label:'OPERATIONS',title:'Convert expert handoffs into reusable standard work.',narrative:'Use structured context and human review to turn recurring operating knowledge into a dependable first draft, checklist, and escalation path.',ai:'Draft, structure, compare',authority:'Process owner approves',governance:'Approved sources; no confidential leakage',measure:'Cycle time, completeness, reuse',motion:'Demo → practice → office hours',verdict:'Standardize',heroVerdict:'Ready to standardize',heroScenario:'Operations knowledge handoff',colors:['#8b69ff','#49a8ff','#20dfc9']},
  talent:{label:'TALENT OPERATIONS',title:'Turn role context into a consistent candidate assessment workflow.',narrative:'Help recruiting teams move from generic prompting to structured role context, evidence-based comparison, human judgment, and traceable decisions.',ai:'Synthesize, compare, prepare',authority:'Recruiter and hiring manager decide',governance:'No sensitive inference; evidence remains attributable',measure:'Intake speed, consistency, rework',motion:'Role clinic → template → calibration',verdict:'Pilot with controls',heroVerdict:'Pilot with controls',heroScenario:'Role-context assessment workflow',colors:['#697dff','#52b9ff','#32ddd5']},
  delivery:{label:'SALES & DELIVERY',title:'Convert discovery into an actionable client-work brief.',narrative:'Use ChatGPT to organize notes, surface open assumptions, draft a structured response, and preserve explicit human ownership of commitments.',ai:'Organize, challenge, draft',authority:'Account and delivery owners commit',governance:'Client data and claims remain bounded',measure:'Handoff speed, clarity, revision load',motion:'Live demo → paired use → review',verdict:'Scale after proof',heroVerdict:'Scale after proof',heroScenario:'Discovery-to-delivery brief',colors:['#3d9cff','#53d0dc','#42dfb3']},
  support:{label:'SUPPORT',title:'Turn recurring issues into earlier, clearer response guidance.',narrative:'Synthesize approved knowledge, identify missing context, draft a response path, and escalate when confidence or consequence requires human judgment.',ai:'Retrieve, summarize, route',authority:'Support owner resolves or escalates',governance:'Approved knowledge; no unsupported diagnosis',measure:'Response time, recurrence, resolution quality',motion:'Case replay → coaching → adoption',verdict:'Standardize selectively',heroVerdict:'Standardize selectively',heroScenario:'Recurring-issue response guidance',colors:['#9a70ff','#57a5ff','#36d9c6']}
};
const fieldIds={label:'scenarioLabel',title:'scenarioTitle',narrative:'scenarioNarrative',ai:'aiRole',authority:'authority',governance:'governance',measure:'measure',motion:'motion',verdict:'verdict'};
const stage=document.getElementById('transformer');
const canvas=document.getElementById('capabilityField');
const announcement=document.getElementById('scenarioAnnouncement');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
const mobile=window.matchMedia('(max-width: 980px), (pointer: coarse) and (max-width: 1100px)');
let scene=null;let selectedScenario='ops';let animationToken=0;
function hexToRgb(hex){const n=Number.parseInt(hex.slice(1),16);return[(n>>16)/255,((n>>8)&255)/255,(n&255)/255]}
function shader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
function perspective(out,fovy,aspect,near,far){const f=1/Math.tan(fovy/2);out.fill(0);out[0]=f/aspect;out[5]=f;out[10]=(far+near)/(near-far);out[11]=-1;out[14]=2*far*near/(near-far);return out}
function lookAt(out,eye,center,up){let zx=eye[0]-center[0],zy=eye[1]-center[1],zz=eye[2]-center[2];let l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx;l=Math.hypot(xx,xy,xz)||1;xx/=l;xy/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;out[0]=xx;out[1]=yx;out[2]=zx;out[3]=0;out[4]=xy;out[5]=yy;out[6]=zy;out[7]=0;out[8]=xz;out[9]=yz;out[10]=zz;out[11]=0;out[12]=-(xx*eye[0]+xy*eye[1]+xz*eye[2]);out[13]=-(yx*eye[0]+yy*eye[1]+yz*eye[2]);out[14]=-(zx*eye[0]+zy*eye[1]+zz*eye[2]);out[15]=1}
function seeded(i){const x=Math.sin(i*12.9898)*43758.5453;return x-Math.floor(x)}
function bezier(a,b,c,d,t){const k=1-t;return[k*k*k*a[0]+3*k*k*t*b[0]+3*k*t*t*c[0]+t*t*t*d[0],k*k*k*a[1]+3*k*k*t*b[1]+3*k*t*t*c[1]+t*t*t*d[1],k*k*k*a[2]+3*k*k*t*b[2]+3*k*t*t*c[2]+t*t*t*d[2]]}
class FunnelScene{
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{alpha:true,antialias:true,powerPreference:'high-performance',premultipliedAlpha:false});if(!this.gl)throw new Error('WebGL2 unavailable');this.progress=1;this.duration=4200;this.start=0;this.raf=0;this.palette=scenarios.ops.colors.map(hexToRgb);this.projection=new Float32Array(16);this.view=new Float32Array(16);lookAt(this.view,[0,.38,7.45],[0,-.12,0],[0,1,0]);this.init();this.ro=new ResizeObserver(()=>this.resize());this.ro.observe(canvas.parentElement)}
  init(){const gl=this.gl;
    const vertexPosition=`float theta=aData.x;float v=aData.y;float r=.36+2.42*pow(v,.55);float twist=(1.0-v)*.22+.035*sin(v*3.14159);float a=theta+twist;float x=r*cos(a);float z=.60*r*sin(a);float y=mix(-1.48,1.42,v);`;
    this.surface=program(gl,`#version 300 es
    precision highp float;layout(location=0)in vec3 aData;uniform mat4 uP,uV;uniform float uProgress;out vec3 vNormal;out vec3 vView;out float vV;out float vSide;out float vA;
    void main(){${vertexPosition}float settle=.93+.07*smoothstep(0.0,.82,uProgress);x*=settle;z*=settle;float dr=1.331*pow(max(v,.001),-.45);vec3 tt=normalize(vec3(-r*sin(a),0.0,.60*r*cos(a)));vec3 tv=normalize(vec3(dr*cos(a)-r*sin(a)*(-.22),2.90,.60*(dr*sin(a)+r*cos(a)*(-.22))));vec3 normal=normalize(cross(tt,tv));vec4 vp=uV*vec4(x,y,z,1.0);gl_Position=uP*vp;vNormal=mat3(uV)*normal;vView=vp.xyz;vV=v;vSide=cos(a)*.5+.5;vA=a;}`,
    `#version 300 es
    precision highp float;in vec3 vNormal;in vec3 vView;in float vV;in float vSide;in float vA;uniform vec3 uA,uB,uC;out vec4 outColor;
    void main(){vec3 n=normalize(vNormal),eye=normalize(-vView);float fres=pow(1.0-max(0.0,dot(n,eye)),2.0);float top=smoothstep(.72,1.0,vV);float throat=1.0-smoothstep(.02,.40,vV);vec3 base=vSide<.5?mix(uA,uB,vSide*2.0):mix(uB,uC,(vSide-.5)*2.0);float sweep=.5+.5*sin(vA*2.0+vV*7.0);float light=.18+.48*fres+.16*top+.14*throat+.06*sweep;float alpha=.16+.22*fres+.075*top+.055*throat;outColor=vec4(base*(.78+light*1.45),alpha);}`);
    this.mesh=program(gl,`#version 300 es
    precision highp float;layout(location=0)in vec3 aData;uniform mat4 uP,uV;out float vSide;out float vV;void main(){${vertexPosition}vec4 vp=uV*vec4(x,y,z,1.0);gl_Position=uP*vp;vSide=cos(a)*.5+.5;vV=v;}`,
    `#version 300 es
    precision highp float;in float vSide;in float vV;uniform vec3 uA,uB,uC;uniform float uAlpha;out vec4 outColor;void main(){vec3 c=vSide<.5?mix(uA,uB,vSide*2.0):mix(uB,uC,(vSide-.5)*2.0);float boost=.78+.38*smoothstep(.65,1.0,vV);outColor=vec4(c*1.58,uAlpha*boost);}`);
    this.worldLines=program(gl,`#version 300 es
    precision highp float;layout(location=0)in vec4 aData;uniform mat4 uP,uV;out float vMix;out float vAlpha;void main(){vec4 vp=uV*vec4(aData.xyz,1.0);gl_Position=uP*vp;vMix=aData.w;vAlpha=.5;}`,
    `#version 300 es
    precision highp float;in float vMix;in float vAlpha;uniform vec3 uA,uB,uC;uniform float uAlpha;out vec4 outColor;void main(){vec3 c=vMix<.5?mix(uA,uB,vMix*2.0):mix(uB,uC,(vMix-.5)*2.0);outColor=vec4(c*1.7,uAlpha*vAlpha);}`);
    this.particles=program(gl,`#version 300 es
    precision highp float;layout(location=0)in vec4 aData;uniform mat4 uP,uV;uniform float uProgress,uTime;out vec3 vColor;out float vAlpha;uniform vec3 uA,uB,uC;
    float ease(float x){return x*x*(3.0-2.0*x);}float hash(float n){return fract(sin(n)*43758.5453123);}vec3 path(float p,float lane,float seed){if(p<.24){float q=p/.24;float yy=mix(lane*.84,1.12+lane*.15,q);float zz=mix((hash(seed*41.0)-.5)*1.16,.12*lane,q);return vec3(mix(-5.15,-2.18,q),yy+sin(seed*91.0+uTime*.82)*.045,zz);}if(p<.78){float q=(p-.24)/.54;float v=1.0-q*.97;float theta=3.14159+lane*.29+(seed-.5)*.28+q*6.65;float r=.36+2.42*pow(v,.55);float a=theta+(1.0-v)*.22;return vec3(r*cos(a),mix(1.42,-1.40,q),.60*r*sin(a));}float q=(p-.78)/.22;return vec3(mix(.12,5.05,q),mix(-1.40,lane*.83,q)+sin((q+seed)*17.0)*.022,mix(0.0,(hash(seed*127.0)-.5)*.16,q));}
    void main(){float seed=aData.x,lane=aData.y;float head=clamp((uProgress-seed*.28)/.72,0.0,1.0);float p=mix(seed*.99,head,aData.z);vec3 pos=path(p,lane,seed);vec4 vp=uV*vec4(pos,1.0);gl_Position=uP*vp;gl_PointSize=aData.w*(5.9/max(1.0,-vp.z));float c=smoothstep(.20,.91,p);vec3 source=mix(uA,uB,lane*.5+.5);vColor=mix(source,uC,c);float moving=smoothstep(0.0,.05,head)*(1.0-smoothstep(.9,1.0,head));float settled=.16+.25*smoothstep(.82,1.0,uProgress);vAlpha=(.34+.64*hash(seed*213.0))*mix(settled,moving,aData.z);}`,
    `#version 300 es
    precision highp float;in vec3 vColor;in float vAlpha;out vec4 outColor;void main(){vec2 uv=gl_PointCoord-.5;float d=length(uv);if(d>.5)discard;float g=pow(smoothstep(.5,0.0,d),2.1);outColor=vec4(vColor*(1.25+g*1.0),vAlpha*g);}`);
    this.buildSurface();this.buildMesh();this.buildWorldLines();this.buildParticles();gl.enable(gl.BLEND);gl.enable(gl.DEPTH_TEST);this.resize()}
  buildSurface(){const gl=this.gl,R=72,S=160,v=[],idx=[];for(let j=0;j<=R;j++)for(let i=0;i<=S;i++)v.push(i/S*Math.PI*2,j/R,0);for(let j=0;j<R;j++)for(let i=0;i<S;i++){const a=j*(S+1)+i,b=a+1,c=(j+1)*(S+1)+i,d=c+1;idx.push(a,c,b,b,c,d)}this.surfaceBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.surfaceBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.STATIC_DRAW);this.indexBuffer=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.indexBuffer);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint32Array(idx),gl.STATIC_DRAW);this.indexCount=idx.length}
  buildMesh(){const gl=this.gl,data=[],draws=[];const add=(arr)=>{const start=data.length/3;data.push(...arr);draws.push([start,arr.length/3])};for(let j=2;j<=68;j+=5){const v=j/72,a=[];for(let i=0;i<=160;i++)a.push(i/160*Math.PI*2,v,0);add(a)}for(let i=0;i<32;i++){const theta=i/32*Math.PI*2,a=[];for(let j=0;j<=72;j++)a.push(theta,j/72,0);add(a)}this.meshBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.meshBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);this.meshDraws=draws}
  buildWorldLines(){const gl=this.gl,data=[],draws=[];const add=(pts)=>{const start=data.length/4;data.push(...pts.flatMap(p=>p));draws.push([start,pts.length])};const ring=(r,y,s=.60,mix=.5)=>{const pts=[];for(let i=0;i<=240;i++){const a=i/240*Math.PI*2;pts.push([r*Math.cos(a),y,s*r*Math.sin(a),Math.max(0,Math.min(1,Math.cos(a)*.5+.5+mix-.5))])}add(pts)};ring(2.75,1.42,.60,.5);ring(2.61,1.38,.60,.5);ring(.48,-1.48,.60,.72);ring(1.26,-1.66,.39,.73);ring(1.72,-1.69,.35,.68);ring(2.1,-1.72,.31,.62);
    const inYs=[.94,.04,-.86],outYs=[.92,.02,-.88];for(let lane=0;lane<3;lane++){let pts=[];for(let i=0;i<=90;i++){const t=i/90,p=bezier([-5.2,inYs[lane],.02],[-4.0,inYs[lane],.2],[-3.0,1.28-lane*.14,.32],[-2.1,1.18-lane*.12,.12],t);pts.push([p[0],p[1],p[2],.12+lane*.16+t*.18])}add(pts);pts=[];for(let i=0;i<=110;i++){const t=i/110,p=bezier([.18,-1.4,0],[1.4,-1.18+lane*.18,.02],[3.2,outYs[lane],.2],[5.2,outYs[lane],.02],t);pts.push([p[0],p[1],p[2],.68+t*.28])}add(pts)}this.worldLineBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.worldLineBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);this.worldLineDraws=draws}
  buildParticles(){const gl=this.gl,count=3900,d=new Float32Array(count*4);for(let i=0;i<count;i++){const lane=(i%3)-1,seed=(i+seeded(i)*.82)/count,moving=i%5===0?1:0;d.set([seed,lane,moving,6.5+seeded(i+17)*11],i*4)}this.particleBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.particleBuffer);gl.bufferData(gl.ARRAY_BUFFER,d,gl.STATIC_DRAW);this.particleCount=count}
  resize(){const r=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.8),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.gl.viewport(0,0,w,h);perspective(this.projection,Math.PI/4.0,w/h,.1,40)}this.render(performance.now())}
  colors(p,time){const gl=this.gl;gl.uniformMatrix4fv(gl.getUniformLocation(p,'uP'),false,this.projection);gl.uniformMatrix4fv(gl.getUniformLocation(p,'uV'),false,this.view);for(const [n,val] of [['uA',this.palette[0]],['uB',this.palette[1]],['uC',this.palette[2]]]){const loc=gl.getUniformLocation(p,n);if(loc)gl.uniform3fv(loc,val)}let loc=gl.getUniformLocation(p,'uProgress');if(loc)gl.uniform1f(loc,this.progress);loc=gl.getUniformLocation(p,'uTime');if(loc)gl.uniform1f(loc,time)}
  setPalette(colors){this.palette=colors.map(hexToRgb)}
  destroy(){cancelAnimationFrame(this.raf);this.ro?.disconnect()}
  replay(){cancelAnimationFrame(this.raf);stage.classList.remove('settled');this.start=performance.now();this.progress=reduced.matches?1:0;if(reduced.matches){this.render(this.start+this.duration);stage.classList.add('settled');return}this.loop(this.start)}
  loop=(now)=>{const t=Math.min(1,(now-this.start)/this.duration);this.progress=1-Math.pow(1-t,3);this.render(now);if(t<1)this.raf=requestAnimationFrame(this.loop);else stage.classList.add('settled')}
  render(now){const gl=this.gl,time=now*.001;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.disable(gl.CULL_FACE);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(this.surface);this.colors(this.surface,time);gl.bindBuffer(gl.ARRAY_BUFFER,this.surfaceBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,12,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.indexBuffer);gl.drawElements(gl.TRIANGLES,this.indexCount,gl.UNSIGNED_INT,0);
    gl.depthMask(false);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.useProgram(this.mesh);this.colors(this.mesh,time);gl.uniform1f(gl.getUniformLocation(this.mesh,'uAlpha'),.42);gl.bindBuffer(gl.ARRAY_BUFFER,this.meshBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,12,0);for(const [start,count] of this.meshDraws)gl.drawArrays(gl.LINE_STRIP,start,count);
    gl.useProgram(this.worldLines);this.colors(this.worldLines,time);gl.uniform1f(gl.getUniformLocation(this.worldLines,'uAlpha'),.24);gl.bindBuffer(gl.ARRAY_BUFFER,this.worldLineBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,16,0);for(const [start,count] of this.worldLineDraws)gl.drawArrays(gl.LINE_STRIP,start,count);
    gl.useProgram(this.particles);this.colors(this.particles,time);gl.bindBuffer(gl.ARRAY_BUFFER,this.particleBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,16,0);gl.drawArrays(gl.POINTS,0,this.particleCount)}
}

function applyPalette(colors){stage.style.setProperty('--a',colors[0]);stage.style.setProperty('--b',colors[1]);stage.style.setProperty('--c',colors[2])}
function ensureRenderer(){if(mobile.matches){scene?.destroy();scene=null;canvas.style.display='none';stage.classList.add('settled');return}canvas.style.display='block';if(scene)return;try{scene=new FunnelScene(canvas);scene.setPalette(scenarios[selectedScenario].colors)}catch(error){console.warn('WebGL2 renderer unavailable; using semantic fallback.',error);scene=null;canvas.style.display='none';stage.classList.add('settled')}}
function applyScenario(key,{announce=true,replay=true}={}){const scenario=scenarios[key];if(!scenario)return;selectedScenario=key;animationToken+=1;Object.entries(fieldIds).forEach(([property,id])=>{const el=document.getElementById(id);if(el)el.textContent=scenario[property]});document.getElementById('heroVerdict').textContent=scenario.heroVerdict;document.getElementById('heroScenario').textContent=scenario.heroScenario;document.getElementById('heroMeasure').textContent=scenario.measure;document.querySelectorAll('[data-scenario]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.scenario===key)));applyPalette(scenario.colors);if(scene){scene.setPalette(scenario.colors);if(replay)scene.replay();else scene.render(performance.now())}else stage.classList.add('settled');if(announce)announcement.textContent=`${scenario.label}: ${scenario.title}. Decision: ${scenario.verdict}.`}
document.querySelectorAll('[data-scenario]').forEach(button=>button.addEventListener('click',()=>applyScenario(button.dataset.scenario)));
document.getElementById('replay')?.addEventListener('click',()=>{const token=++animationToken;if(scene)scene.replay();else{stage.classList.remove('settled');requestAnimationFrame(()=>stage.classList.add('settled'))}announcement.textContent=`Replaying ${scenarios[selectedScenario].label.toLowerCase()} transformation.`;setTimeout(()=>{if(token===animationToken)announcement.textContent=`${scenarios[selectedScenario].heroVerdict}.`},reduced.matches?0:4300)});
document.getElementById('resetScenario')?.addEventListener('click',()=>applyScenario('ops'));
mobile.addEventListener?.('change',()=>{ensureRenderer();applyScenario(selectedScenario,{announce:false,replay:Boolean(scene)})});
reduced.addEventListener?.('change',()=>{if(scene)scene.replay();else stage.classList.add('settled')});
ensureRenderer();applyScenario('ops',{announce:false,replay:true});
